<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = collect([
            [
                "name" => "Moises",
                "last_name" => "Perez",
                "phone_number" => "(12)111111111",
                "profile_photo_path" => null,
                "email" => "m.perez@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => "2020-01-10 17:20:58",
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2019-12-18 18:14:36",
                "modified" => "2021-12-18 05:37:09",
                "company_contact" => "",
                "credits" => 10035.00,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => 2,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Jordi",
                "last_name" => "T",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "pruebas2@amobasoftware.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => "NUOlOJYc4viPLu207GM2DtMS1DdjZLmy5uXVGW8BqS163U34Xeiv3AF3R6bi",
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Josep",
                "last_name" => "R",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+2@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Carme",
                "last_name" => "F",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+3@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Oriol",
                "last_name" => "J",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+4@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Jordi",
                "last_name" => "C",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+5@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Jordi",
                "last_name" => "S",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+6@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => null,
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Dolors",
                "last_name" => "B",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "m.perez+7@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => "2021-05-20 17:58:55",
                "company_contact" => null,
                "credits" => 200.00,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "Raul",
                "last_name" => "R",
                "phone_number" => "",
                "profile_photo_path" => null,
                "email" => "pruebas@amobasoftware.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => "hl2mLGO7gooDsGnCVerT1ijCSCPFL97aL3Up46D3bORJM34YiTOIaUHya9Ib",
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => null,
                "modified" => "2021-05-20 17:58:46",
                "company_contact" => null,
                "credits" => 200.00,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "EasyCourse",
                "last_name" => "EasyCourse",
                "phone_number" => null,
                "profile_photo_path" => null,
                "email" => "easycourse@busup.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-04-10 11:31:19",
                "modified" => "2021-04-10 11:31:19",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => 6,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "nelson jose",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "jojoto@jojoto.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-12 20:14:20",
                "modified" => "2021-06-27 05:32:13",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "jojoto perez",
                "last_name" => "",
                "phone_number" => "999999999999",
                "profile_photo_path" => null,
                "email" => "jojoto@jojort.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-22 01:08:37",
                "modified" => "2021-06-22 01:08:37",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "jojoto perez",
                "last_name" => "",
                "phone_number" => "96999999",
                "profile_photo_path" => null,
                "email" => "jojoto@jojojoto.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-22 20:56:47",
                "modified" => "2021-06-22 20:56:47",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "georgina",
                "last_name" => "",
                "phone_number" => "5555555",
                "profile_photo_path" => null,
                "email" => "georgina@georgina.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-24 03:27:57",
                "modified" => "2021-06-24 03:27:58",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "jojoto peorez",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "jojoto@joto.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-25 00:42:22",
                "modified" => "2021-06-25 00:42:23",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "nelson jose",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "nelson@nelson.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-25 17:34:04",
                "modified" => "2021-06-25 17:34:04",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "nelsonfariasba@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-26 15:50:34",
                "modified" => "2021-06-26 15:50:34",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "nelson jose",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "jose@jose.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-06-27 04:49:43",
                "modified" => "2021-06-27 04:49:43",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "Daniel Sanchez",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "ingdanieljs@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-08-01 21:55:37",
                "modified" => "2021-08-01 21:55:37",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "Daniel Sanchez",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "2ingdanieljs@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-08-01 22:19:30",
                "modified" => "2021-08-01 22:58:26",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "jojoto gates",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "jojoto@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-08-01 23:03:28",
                "modified" => "2021-08-01 23:03:28",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "Daniel Sanchez",
                "last_name" => "",
                "phone_number" => "34 12345767",
                "profile_photo_path" => null,
                "email" => "3ingdanieljs@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => -1,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-08-01 23:08:19",
                "modified" => "2021-08-01 23:08:19",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => null,
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ],
            [
                "name" => "aaaaaa",
                "last_name" => "qqqqq",
                "phone_number" => "(34)12345678",
                "profile_photo_path" => null,
                "email" => "daniel2@prueba.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-09-15 03:21:58",
                "modified" => "2021-09-15 03:21:58",
                "company_contact" => null,
                "credits" => 0.00,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => "614166d60d77e",
                "user_vertical" => null,
                "language_id" => 2,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "nelson",
                "last_name" => "bucaranda",
                "phone_number" => "(593)987116649",
                "profile_photo_path" => null,
                "email" => "nelson@amobasoftware.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-10-30 07:56:19",
                "modified" => "2021-12-18 06:14:38",
                "company_contact" => null,
                "credits" => 7850.00,
                "first_trip" => 0,
                "incomplete_profile" => 0,
                "phone_verify" => 1,
                "token_auto_login" => "617cfaa34b62f",
                "user_vertical" => null,
                "language_id" => 4,
                "no_registered" => 0,
                "deleted_at" => null,
            ],
            [
                "name" => "jojota perez",
                "last_name" => null,
                "phone_number" => null,
                "profile_photo_path" => null,
                "email" => "jojota@gmail.com",
                "password" => 'e10adc3949ba59abbe56e057f20f883e',
                "remember_token" => null,
                "last_online" => null,
                "verification_code" => null,
                "new_email" => null,
                "status" => 2,
                "first" => 0,
                "last_accept_date" => null,
                "created" => "2021-11-12 03:21:54",
                "modified" => "2021-11-12 03:21:54",
                "company_contact" => null,
                "credits" => null,
                "first_trip" => 0,
                "incomplete_profile" => 1,
                "phone_verify" => 0,
                "token_auto_login" => "618dddd2102fe",
                "user_vertical" => null,
                "language_id" => null,
                "no_registered" => 1,
                "deleted_at" => null,
            ]
        ]);

        $users->each(fn ($user) => User::create($user));
    }
}
